/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.galvanize; // says what this namespace belongs to...
import java.lang.Math;

public class App {
    public String getGreeting() {
        return "Hello world. Thank you Rob!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        double val = 4.567;

        long roundedVal = Math.round(val);

        System.out.println("Rounded value is " + roundedVal);

        // this.roundNumber();
    }

    public  void roundNumber()
    {

    }
}
